version: "3.8"
services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=movieverse
    depends_on:
      - db
    networks:
      - movieverse-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movieverse
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./be/movieverse.sql:/docker-entrypoint-initdb.d/movieverse.sql
    networks:
      - movieverse-network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "5173:80" # URL frontend: http://localhost:5173
    networks:
      - movieverse-network
    depends_on:
      - backend
      
networks:
  movieverse-network:

volumes:
  db_data:
